# Generated by Django 3.2.6 on 2021-08-11 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.game'),
        ),
        migrations.AddField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.player'),
        ),
        migrations.AddField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.game'),
        ),
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.player'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=1, verbose_name=''),
            preserve_default=False,
        ),
    ]
